// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: person.proto

package pkg

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Person_Type int32

const (
	Person_PENDING Person_Type = 0
	Person_ACTIVE  Person_Type = 1
	Person_EXPIRED Person_Type = 2
)

var Person_Type_name = map[int32]string{
	0: "PENDING",
	1: "ACTIVE",
	2: "EXPIRED",
}

var Person_Type_value = map[string]int32{
	"PENDING": 0,
	"ACTIVE":  1,
	"EXPIRED": 2,
}

func (x Person_Type) String() string {
	return proto.EnumName(Person_Type_name, int32(x))
}

func (Person_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0, 0}
}

type Person struct {
	Id        string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled   bool                 `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Type      int32                `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Name      string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Person) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Person) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Person_Id struct {
	// Check for valid ObjectId
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *Person_Id) Reset()         { *m = Person_Id{} }
func (m *Person_Id) String() string { return proto.CompactTextString(m) }
func (*Person_Id) ProtoMessage()    {}
func (*Person_Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0, 0}
}
func (m *Person_Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_Id.Unmarshal(m, b)
}
func (m *Person_Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_Id.Marshal(b, m, deterministic)
}
func (m *Person_Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_Id.Merge(m, src)
}
func (m *Person_Id) XXX_Size() int {
	return xxx_messageInfo_Person_Id.Size(m)
}
func (m *Person_Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Person_Id proto.InternalMessageInfo

func (m *Person_Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Person_Filters struct {
	Enabled bool  `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Type    int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Skip    int32 `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit   int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *Person_Filters) Reset()         { *m = Person_Filters{} }
func (m *Person_Filters) String() string { return proto.CompactTextString(m) }
func (*Person_Filters) ProtoMessage()    {}
func (*Person_Filters) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0, 1}
}
func (m *Person_Filters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_Filters.Unmarshal(m, b)
}
func (m *Person_Filters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_Filters.Marshal(b, m, deterministic)
}
func (m *Person_Filters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_Filters.Merge(m, src)
}
func (m *Person_Filters) XXX_Size() int {
	return xxx_messageInfo_Person_Filters.Size(m)
}
func (m *Person_Filters) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_Filters.DiscardUnknown(m)
}

var xxx_messageInfo_Person_Filters proto.InternalMessageInfo

func (m *Person_Filters) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Person_Filters) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Person_Filters) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *Person_Filters) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Persons struct {
	Items []*Person `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (m *Persons) Reset()         { *m = Persons{} }
func (m *Persons) String() string { return proto.CompactTextString(m) }
func (*Persons) ProtoMessage()    {}
func (*Persons) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}
func (m *Persons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Persons.Unmarshal(m, b)
}
func (m *Persons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Persons.Marshal(b, m, deterministic)
}
func (m *Persons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Persons.Merge(m, src)
}
func (m *Persons) XXX_Size() int {
	return xxx_messageInfo_Persons.Size(m)
}
func (m *Persons) XXX_DiscardUnknown() {
	xxx_messageInfo_Persons.DiscardUnknown(m)
}

var xxx_messageInfo_Persons proto.InternalMessageInfo

func (m *Persons) GetItems() []*Person {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterEnum("pkg.Person_Type", Person_Type_name, Person_Type_value)
	proto.RegisterType((*Person)(nil), "pkg.Person")
	proto.RegisterType((*Person_Id)(nil), "pkg.Person.Id")
	proto.RegisterType((*Person_Filters)(nil), "pkg.Person.Filters")
	proto.RegisterType((*Persons)(nil), "pkg.Persons")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0x4e, 0xd2, 0x36, 0xf5, 0xb6, 0xe7, 0x59, 0xd7, 0x43, 0x42, 0x94, 0x5a, 0x43, 0xc1, 0xa2,
	0xd7, 0x14, 0xa2, 0x0f, 0xbe, 0xb6, 0xd7, 0x78, 0x04, 0xe4, 0x28, 0xb1, 0x8a, 0xe0, 0x0f, 0xd8,
	0x36, 0x73, 0x71, 0x69, 0x92, 0x5d, 0x92, 0xed, 0x61, 0x11, 0xff, 0x02, 0x5f, 0xfc, 0xd3, 0x7c,
	0xf4, 0xbd, 0xff, 0x85, 0x4f, 0x92, 0x4d, 0x7a, 0x97, 0x6b, 0x05, 0xdf, 0x66, 0xe6, 0xfb, 0xbe,
	0x9d, 0xf9, 0x66, 0x16, 0x1d, 0x72, 0x48, 0x33, 0x96, 0xd8, 0x3c, 0x65, 0x82, 0xe1, 0x1a, 0x5f,
	0x86, 0xe6, 0xc3, 0x90, 0xb1, 0x30, 0x82, 0x21, 0xe1, 0x74, 0x48, 0x92, 0x84, 0x09, 0x22, 0x28,
	0x4b, 0xb2, 0x82, 0x62, 0x0e, 0x42, 0x2a, 0xbe, 0xac, 0xe6, 0xf6, 0x82, 0xc5, 0xc3, 0x90, 0x85,
	0x6c, 0x28, 0xcb, 0xf3, 0xd5, 0x85, 0xcc, 0x64, 0x22, 0xa3, 0x92, 0x3e, 0xaa, 0xd0, 0x21, 0xb9,
	0x64, 0x6b, 0x9e, 0xb2, 0xaf, 0xeb, 0x42, 0xb4, 0x18, 0x84, 0x90, 0x0c, 0x2e, 0x49, 0x44, 0x03,
	0x22, 0x60, 0xb8, 0x17, 0x94, 0x4f, 0x3c, 0x28, 0xe7, 0xb9, 0x6a, 0x04, 0x31, 0x17, 0xeb, 0x12,
	0x7c, 0xb4, 0x0b, 0x0a, 0x1a, 0x43, 0x26, 0x48, 0xcc, 0x0b, 0x82, 0xf5, 0xa3, 0x86, 0xf4, 0xa9,
	0xf4, 0x88, 0x8f, 0x90, 0x46, 0x03, 0x43, 0xed, 0xaa, 0xfd, 0x03, 0x5f, 0xa3, 0x01, 0x36, 0x50,
	0x13, 0x12, 0x32, 0x8f, 0x20, 0x30, 0xb4, 0xae, 0xda, 0xbf, 0xe5, 0x6f, 0x53, 0x8c, 0x51, 0x5d,
	0xac, 0x39, 0x18, 0xb5, 0xae, 0xda, 0x6f, 0xf8, 0x32, 0xce, 0x6b, 0x09, 0x89, 0xc1, 0xa8, 0x4b,
	0xbd, 0x8c, 0xf1, 0x4b, 0x74, 0xb0, 0x48, 0x81, 0x08, 0x08, 0x46, 0xc2, 0x68, 0x74, 0xd5, 0x7e,
	0xcb, 0x31, 0xed, 0x62, 0x22, 0x7b, 0x3b, 0x91, 0x3d, 0xdb, 0x4e, 0xe4, 0x5f, 0x93, 0x73, 0xe5,
	0x8a, 0x07, 0xa5, 0x52, 0xff, 0xbf, 0xf2, 0x8a, 0x6c, 0x3e, 0x45, 0x9a, 0x17, 0xe0, 0xde, 0xb5,
	0x97, 0xf1, 0xf1, 0x9f, 0xf1, 0xdd, 0xf4, 0x8e, 0x73, 0xfb, 0xf3, 0x07, 0x32, 0xb8, 0xf8, 0x18,
	0x7c, 0xfa, 0xe6, 0xbc, 0xf8, 0xde, 0xcb, 0x1d, 0x9a, 0x04, 0x35, 0x5f, 0xd1, 0x48, 0x40, 0x9a,
	0x55, 0xcd, 0xaa, 0xff, 0x36, 0xab, 0xdd, 0x34, 0x9b, 0x2d, 0x29, 0xdf, 0x2e, 0x20, 0x8f, 0xf1,
	0x31, 0x6a, 0x44, 0x34, 0xa6, 0x42, 0x6e, 0xa0, 0xe1, 0x17, 0x89, 0x75, 0x82, 0xea, 0xb3, 0x5c,
	0xd1, 0x42, 0xcd, 0xa9, 0x7b, 0x3e, 0xf1, 0xce, 0xcf, 0xda, 0x0a, 0x46, 0x48, 0x1f, 0x9d, 0xce,
	0xbc, 0x77, 0x6e, 0x5b, 0xcd, 0x01, 0xf7, 0xfd, 0xd4, 0xf3, 0xdd, 0x49, 0x5b, 0xb3, 0x4e, 0x50,
	0xb3, 0x38, 0x46, 0x86, 0x1f, 0xa3, 0x06, 0x15, 0x10, 0x67, 0x86, 0xda, 0xad, 0xf5, 0x5b, 0x4e,
	0xcb, 0xe6, 0xcb, 0xd0, 0x2e, 0x40, 0xbf, 0x40, 0x9c, 0x8d, 0x8a, 0x5a, 0x45, 0xe5, 0x8d, 0x60,
	0x29, 0xe0, 0x27, 0x48, 0x3f, 0x95, 0x1b, 0xc4, 0x55, 0xb6, 0x79, 0x54, 0x49, 0x6c, 0x2f, 0xb0,
	0x14, 0xdc, 0x43, 0xb5, 0x33, 0x10, 0x78, 0x07, 0x30, 0xab, 0x2a, 0x4b, 0xc1, 0xcf, 0x50, 0xfd,
	0x35, 0xcd, 0x04, 0xbe, 0x57, 0xa5, 0x95, 0xfb, 0x32, 0x0f, 0x2b, 0xc5, 0x4c, 0x3e, 0xa9, 0xbf,
	0x95, 0x37, 0xb8, 0xd9, 0x7b, 0xe7, 0x49, 0x07, 0xe9, 0x13, 0x88, 0x40, 0xc0, 0x5e, 0xef, 0xfb,
	0x7b, 0xd7, 0x75, 0xf3, 0x6f, 0x6c, 0x29, 0xe3, 0xc3, 0x9f, 0x9b, 0x8e, 0xf2, 0x6b, 0xd3, 0x51,
	0x7e, 0x6f, 0x3a, 0xca, 0x5c, 0x97, 0xf8, 0xf3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x6c,
	0x9e, 0xfc, 0x99, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonStoreClient is the client API for PersonStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonStoreClient interface {
	Create(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person_Id, error)
	Get(ctx context.Context, in *Person_Id, opts ...grpc.CallOption) (*Person, error)
	List(ctx context.Context, in *Person_Filters, opts ...grpc.CallOption) (*Persons, error)
	Update(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
	Delete(ctx context.Context, in *Person_Id, opts ...grpc.CallOption) (*empty.Empty, error)
}

type personStoreClient struct {
	cc *grpc.ClientConn
}

func NewPersonStoreClient(cc *grpc.ClientConn) PersonStoreClient {
	return &personStoreClient{cc}
}

func (c *personStoreClient) Create(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person_Id, error) {
	out := new(Person_Id)
	err := c.cc.Invoke(ctx, "/pkg.PersonStore/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personStoreClient) Get(ctx context.Context, in *Person_Id, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/pkg.PersonStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personStoreClient) List(ctx context.Context, in *Person_Filters, opts ...grpc.CallOption) (*Persons, error) {
	out := new(Persons)
	err := c.cc.Invoke(ctx, "/pkg.PersonStore/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personStoreClient) Update(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/pkg.PersonStore/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personStoreClient) Delete(ctx context.Context, in *Person_Id, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pkg.PersonStore/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonStoreServer is the server API for PersonStore service.
type PersonStoreServer interface {
	Create(context.Context, *Person) (*Person_Id, error)
	Get(context.Context, *Person_Id) (*Person, error)
	List(context.Context, *Person_Filters) (*Persons, error)
	Update(context.Context, *Person) (*Person, error)
	Delete(context.Context, *Person_Id) (*empty.Empty, error)
}

// UnimplementedPersonStoreServer can be embedded to have forward compatible implementations.
type UnimplementedPersonStoreServer struct {
}

func (*UnimplementedPersonStoreServer) Create(ctx context.Context, req *Person) (*Person_Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedPersonStoreServer) Get(ctx context.Context, req *Person_Id) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedPersonStoreServer) List(ctx context.Context, req *Person_Filters) (*Persons, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedPersonStoreServer) Update(ctx context.Context, req *Person) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedPersonStoreServer) Delete(ctx context.Context, req *Person_Id) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterPersonStoreServer(s *grpc.Server, srv PersonStoreServer) {
	s.RegisterService(&_PersonStore_serviceDesc, srv)
}

func _PersonStore_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonStoreServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pkg.PersonStore/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonStoreServer).Create(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person_Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pkg.PersonStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonStoreServer).Get(ctx, req.(*Person_Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonStore_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person_Filters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonStoreServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pkg.PersonStore/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonStoreServer).List(ctx, req.(*Person_Filters))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonStore_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonStoreServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pkg.PersonStore/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonStoreServer).Update(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person_Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pkg.PersonStore/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonStoreServer).Delete(ctx, req.(*Person_Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.PersonStore",
	HandlerType: (*PersonStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PersonStore_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PersonStore_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PersonStore_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PersonStore_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PersonStore_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "person.proto",
}
